<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ForceSignal.Application\ForceSignal.Application.csproj" />
    <ProjectReference Include="..\ForceSignal.Infrastructure\ForceSignal.Infrastructure.csproj" />
    <ProjectReference Include="..\ForceSignal.Contracts\ForceSignal.Contracts.csproj" />
  </ItemGroup>

</Project>
